---
ansible_ssh_pass: "{{ crypt_ansible_ssh_pass }}"
ansible_become_pass: "{{ crypt_ansible_become_pass }}"
ansible_sudo_pass: "{{ crypt_ansible_sudo_pass }}"

hostname: "{{ inventory_hostname }}"
# ubuntuの日本語Remix入れるかどうかのフラグ
japanease: false
hosts:
  # /etc/hostsに設定するホスト情報
  etc_hosts_setting:
    - { name: "{{ hostname }}", ip: 127.0.0.1 }
    - { name: "raspi.test", ip: 172.16.100.254 }
    - { name: "raspi-master1.test", ip: 172.16.100.131 }
    - { name: "raspi-worker1.test", ip: 172.16.100.132 }
    - { name: "raspi-worker2.test", ip: 172.16.100.133 }
    - { name: "raspi-worker3.test", ip: 172.16.100.134 }

# 各ミドルウェアのインストール・設定フラグ
# docker
docker_install: true
docker_remote_api_enable: "no"
# firewall
firewall: true
package_control_auto_reboot: "true"

# SSHログイン時にメール送付しないグローバルIP
# IPは正規表現でマッチ。接続元IPがここで定義したip正規表現と一致すればメールが送られない
ssh_mail_send: "true"
script_dir: "/usr/local/script"
ssh_mail_send_trust_list_file: /usr/local/ssh_mail_send_trust_list
ssh_mail_send_no_send_ip_list:
  - { ip: 127.0.0.1 }
  - { ip: 192.168. }
  - { ip: 172.16. }
  - { ip: 172.17. }
  - { ip: 172.18. }
  - { ip: 172.19. }
  - { ip: 172.20. }
  - { ip: 172.28. }
  - { ip: 172.31. }
  - { ip: 10.0.2. }
  # 自宅IP
  - { ip: 61.213.68.235 }

# ユーザ関連
manage_user_name: toshi
manage_user_group: toshi
manage_user_password: "{{ crypt_manage_user_pass }}"
# manageユーザのsudo NOパスワードを許容するか
sudo_nopassword: "yes"
root_user_password: "{{ crypt_root_user_pass }}"
ansible_user_password: "{{ crypt_ansible_user_password }}"

# モニタリング
mail_transfer_address: "{{ crypt_mail_transfer_address }}"
slack_web_hook_url: "{{ crypt_slack_web_hook_url }}"

# fluentd 中継サーバーの情報
fluentd_send_server_name: "{{ crypt_fluentd_send_server_name }}"
fluentd_send_server_port: "{{ crypt_fluentd_send_server_port }}"
fluentd_send_server_shared_key: "{{ crypt_fluentd_send_server_shared_key }}"
fluentd_send_server_private_key_passphrase: "{{ crypt_fluentd_send_server_private_key_passphrase }}"

# このプロジェクトが設置される親ディレクトリ
project_root_dir: /app
# 証明書ファイルの場所
project_cert_dir: "{{ project_root_dir }}/certs"
project_name: "{{ inventory_hostname }}"
stage: "prd"
project_dir: "{{ project_root_dir }}/{{ project_name }}"
deploy_dir: "{{ project_dir }}"

cron_setting: false

docker_compose_deploy: false
# xrdpをインストールするかどうかのフラグ デスクトップ環境がいる場合はtrueで
xrdp_install: false
# fluentdをインストールするか
fluentd_install: false
fluentd_user: root
fluentd_group: root
fluentd_gcp_flag: false
fluentd_gcp_key_file: "/etc/td-agent/application_default_credentials.json"

samba_allow_ip: "127. 172.28 172.16"
samba_interfaces: "127.0.0.0/8 172.16.0.0/16 172.28.0.0/16 192.168.0.0/16"
samba_users:
  - name: toshi
    password: "{{ crypt_toshi_samba_users_pass }}"
  - name: seiri
    password: "{{ crypt_seiri_samba_users_pass }}"
samba_shares:
  - name: share
    comment: '/share/share'
    path: /share/share
    read_only: no
    guest_ok: no
    write_list: toshi
    owner: toshi
samba_only_users:
  - seiri
xrdp_users:
  - {name: toshi}
