---
server_group: ""
common_ssh_id_rsa_path: "{{ inventory_dir }}/files/toshi_sshkey"
common_ssh_git_key_path: "{{ inventory_dir }}/files/gitkey"
ansible_ssh_pass: "{{ crypt_ansible_ssh_pass }}"
ansible_become_pass: "{{ crypt_ansible_become_pass }}"
ansible_sudo_pass: "{{ crypt_ansible_sudo_pass }}"

hostname: "{{ inventory_hostname }}"

hosts:
  # /etc/hostsに設定するホスト情報
  etc_hosts_setting:
    - { name: "{{ hostname }}", ip: 127.0.0.1 }
    - { name: "raspi.test", ip: 172.16.100.254 }
    - { name: "rasdev.test", ip: 172.16.100.253 }
    - { name: "raspi-master1.test", ip: 172.16.100.131 }
    - { name: "raspi-worker1.test", ip: 172.16.100.132 }
    - { name: "raspi-worker2.test", ip: 172.16.100.133 }
    - { name: "raspi-worker3.test", ip: 172.16.100.134 }

# 各ミドルウェアのインストール・設定フラグ
# docker
docker_install: true
docker_remote_api_enable: "no"
# firewall
firewall: true

# ユーザ関連
manage_user_name: toshi
manage_user_group: toshi
manage_user_password: "{{ crypt_manage_user_pass }}"
# manageユーザのsudo NOパスワードを許容するか
sudo_nopassword: "yes"
root_user_password: "{{ crypt_root_user_pass }}"
ansible_user_password: "{{ crypt_ansible_user_password }}"

# モニタリング
mail_transfer_address: "{{ crypt_mail_transfer_address }}"

samba_interfaces: "172.16.0.0/16 192.168.101.71/24 192.168.101.72/24"
samba_users:
  - name: toshi
    password: "{{ crypt_toshi_samba_users_pass }}"
  - name: seiri
    password: "{{ crypt_seiri_samba_users_pass }}"
samba_shares:
  - name: share
    comment: '/share/share'
    path: /share/share
    read_only: no
    guest_ok: no
    write_list: toshi
    owner: toshi
samba_only_users:
  - seiri

github_private_access_token: "{{ crypt_github_access_token }}"
github_org_access_token: "{{ crypt_github_org_access_token }}"
github_runner_labels: []




# ローカル以外VPN経由ルール
wire_guard_default_forward_address: 0.0.0.0/5, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/3, 64.0.0.0/2, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 192.168.101.0/24

wire_guard_server_private_key: "{{ crypt_wire_guard_server_private_key }}"
wire_guard_server_public_key: M0WSPoqUVs1OBAXhBYr/MtQE8AhQoLlwSAW+FL5RZGk=
wire_guard_clients:
  - name: toshipc01
    private_key: "{{ crypt_wire_guard_client_toshipc01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc01_preshared_key }}"
    ip_address: 192.168.101.10
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: toshipc02
    private_key: "{{ crypt_wire_guard_client_toshipc02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc02_preshared_key }}"
    ip_address: 192.168.101.11
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: smartphone01
    private_key: "{{ crypt_wire_guard_client_smartphone01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone01_preshared_key }}"
    ip_address: 192.168.101.21
    forward_address: 0.0.0.0/0
  - name: smartphone02
    private_key: "{{ crypt_wire_guard_client_smartphone02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone02_preshared_key }}"
    ip_address: 192.168.101.22
    forward_address: 0.0.0.0/0
  - name: other01
    private_key: "{{ crypt_wire_guard_client_other01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_other01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_other01_preshared_key }}"
    ip_address: 192.168.101.99
    forward_address: 0.0.0.0/0
  - name: shigure
    private_key: "{{ crypt_wire_guard_client_shigure_private_key }}"
    public_key: "{{ crypt_wire_guard_client_shigure_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_shigure_preshared_key }}"
    ip_address: 192.168.101.71
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: mayu
    private_key: "{{ crypt_wire_guard_client_mayu_private_key }}"
    public_key: "{{ crypt_wire_guard_client_mayu_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_mayu_preshared_key }}"
    ip_address: 192.168.101.72
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: ranko
    private_key: "{{ crypt_wire_guard_client_ranko_private_key }}"
    public_key: "{{ crypt_wire_guard_client_ranko_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_ranko_preshared_key }}"
    ip_address: 192.168.101.73
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: qnapmain
    private_key: "{{ crypt_wire_guard_client_qnapmain_private_key }}"
    public_key: "{{ crypt_wire_guard_client_qnapmain_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_qnapmain_preshared_key }}"
    ip_address: 192.168.101.91
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: qnapsub
    private_key: "{{ crypt_wire_guard_client_qnapsub_private_key }}"
    public_key: "{{ crypt_wire_guard_client_qnapsub_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_qnapsub_preshared_key }}"
    ip_address: 192.168.101.92
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: mother
    private_key: "{{ crypt_wire_guard_client_mother_private_key }}"
    public_key: "{{ crypt_wire_guard_client_mother_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_mother_preshared_key }}"
    ip_address: 192.168.101.201
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: sister1
    private_key: "{{ crypt_wire_guard_client_sister1_private_key }}"
    public_key: "{{ crypt_wire_guard_client_sister1_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_sister1_preshared_key }}"
    ip_address: 192.168.101.202
    forward_address: 192.168.101.0/24
  - name: sister2
    private_key: "{{ crypt_wire_guard_client_sister2_private_key }}"
    public_key: "{{ crypt_wire_guard_client_sister2_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_sister2_preshared_key }}"
    ip_address: 192.168.101.203
    forward_address: 192.168.101.0/24

  - name: raspi
    private_key: "{{ crypt_wire_guard_client_raspi_private_key }}"
    public_key: "{{ crypt_wire_guard_client_raspi_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_raspi_preshared_key }}"
    ip_address: 192.168.101.51
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: rasdev
    private_key: "{{ crypt_wire_guard_client_rasdev_private_key }}"
    public_key: "{{ crypt_wire_guard_client_rasdev_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_rasdev_preshared_key }}"
    ip_address: 192.168.101.52
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: sae
    private_key: "{{ crypt_wire_guard_client_sae_private_key }}"
    public_key: "{{ crypt_wire_guard_client_sae_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_sae_preshared_key }}"
    ip_address: 192.168.101.53
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: kaede
    private_key: "{{ crypt_wire_guard_client_kaede_private_key }}"
    public_key: "{{ crypt_wire_guard_client_kaede_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_kaede_preshared_key }}"
    ip_address: 192.168.101.54
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: shiki
    private_key: "{{ crypt_wire_guard_client_shiki_private_key }}"
    public_key: "{{ crypt_wire_guard_client_shiki_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_shiki_preshared_key }}"
    ip_address: 192.168.101.55
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: kako
    private_key: "{{ crypt_wire_guard_client_kako_private_key }}"
    public_key: "{{ crypt_wire_guard_client_kako_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_kako_preshared_key }}"
    ip_address: 192.168.101.56
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: ayaka
    private_key: "{{ crypt_wire_guard_client_ayaka_private_key }}"
    public_key: "{{ crypt_wire_guard_client_ayaka_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_ayaka_preshared_key }}"
    ip_address: 192.168.101.57
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: other2
    private_key: "{{ crypt_wire_guard_client_other2_private_key }}"
    public_key: "{{ crypt_wire_guard_client_other2_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_other2_preshared_key }}"
    ip_address: 192.168.101.58
    forward_address: "{{ wire_guard_default_forward_address }}"
  - name: other3
    private_key: "{{ crypt_wire_guard_client_other3_private_key }}"
    public_key: "{{ crypt_wire_guard_client_other3_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_other3_preshared_key }}"
    ip_address: 192.168.101.59
    forward_address: "{{ wire_guard_default_forward_address }}"
