---
server_group: ""
common_ssh_id_rsa_path: "{{ inventory_dir }}/files/toshi_sshkey"
common_ssh_git_key_path: "{{ inventory_dir }}/files/gitkey"
ansible_ssh_pass: "{{ crypt_ansible_ssh_pass }}"
ansible_become_pass: "{{ crypt_ansible_become_pass }}"
ansible_sudo_pass: "{{ crypt_ansible_sudo_pass }}"

hostname: "{{ inventory_hostname }}"

hosts:
  # /etc/hostsに設定するホスト情報
  etc_hosts_setting:
    - { name: "{{ hostname }}", ip: 127.0.0.1 }
    - { name: "raspi.test", ip: 172.16.100.254 }
    - { name: "rasdev.test", ip: 172.16.100.253 }
    - { name: "raspi-master1.test", ip: 172.16.100.131 }
    - { name: "raspi-worker1.test", ip: 172.16.100.132 }
    - { name: "raspi-worker2.test", ip: 172.16.100.133 }
    - { name: "raspi-worker3.test", ip: 172.16.100.134 }

# 各ミドルウェアのインストール・設定フラグ
# docker
docker_install: true
docker_remote_api_enable: "no"
# firewall
firewall: true

# ユーザ関連
manage_user_name: toshi
manage_user_group: toshi
manage_user_password: "{{ crypt_manage_user_pass }}"
# manageユーザのsudo NOパスワードを許容するか
sudo_nopassword: "yes"
root_user_password: "{{ crypt_root_user_pass }}"
ansible_user_password: "{{ crypt_ansible_user_password }}"

# モニタリング
mail_transfer_address: "{{ crypt_mail_transfer_address }}"

samba_interfaces: "127.0.0.0/8 172.16.0.0/16 172.28.0.0/16 172.28.177.0/24 192.168.0.0/16"
samba_users:
  - name: toshi
    password: "{{ crypt_toshi_samba_users_pass }}"
  - name: seiri
    password: "{{ crypt_seiri_samba_users_pass }}"
samba_shares:
  - name: share
    comment: '/share/share'
    path: /share/share
    read_only: no
    guest_ok: no
    write_list: toshi
    owner: toshi
samba_only_users:
  - seiri

github_private_access_token: "{{ crypt_github_access_token }}"
github_org_access_token: "{{ crypt_github_org_access_token }}"
github_runner_labels: []

wire_guard_server_host: "{{ crypt_wire_guard_server_host }}"
wire_guard_server_private_key: "{{ crypt_wire_guard_server_private_key }}"
wire_guard_server_public_key: M0WSPoqUVs1OBAXhBYr/MtQE8AhQoLlwSAW+FL5RZGk=
wire_guard_server_wan_interface: wlan0
wire_guard_clients:
  - name: toshipc01
    private_key: "{{ crypt_wire_guard_client_toshipc01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc01_preshared_key }}"
    ip_address: 172.16.101.10
  - name: toshipc02
    private_key: "{{ crypt_wire_guard_client_toshipc02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc02_preshared_key }}"
    ip_address: 172.16.101.11
  - name: smartphone01
    private_key: "{{ crypt_wire_guard_client_smartphone01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone01_preshared_key }}"
    ip_address: 172.16.101.101
  - name: smartphone02
    private_key: "{{ crypt_wire_guard_client_smartphone02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone02_preshared_key }}"
    ip_address: 172.16.101.102
  - name: other01
    private_key: "{{ crypt_wire_guard_client_other01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_other01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_other01_preshared_key }}"
    ip_address: 172.16.101.201
