[config]
model = "vertex_ai/gemini-1.5-flash"
model_turbo = "vertex_ai/gemini-1.5-flash"
fallback_models="vertex_ai/gemini-1.5-flash"

[pr_reviewer] # /review #
extra_instructions = "Please use Japanese for everything."

[pr_description] # /describe #
add_original_user_description = true
extra_instructions = "Please use Japanese for everything.  Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc"

[pr_code_suggestions] # /improve #
extra_instructions = "Please use Japanese for everything."

[pr_add_docs] # /add_docs #
extra_instructions = "Please use Japanese for everything."

[pr_update_changelog] # /update_changelog #
extra_instructions = "Please use Japanese for everything."

[pr_test] # /test #
extra_instructions = "Please use Japanese for everything."

[pr_improve_component] # /improve_component #
extra_instructions = "Please use Japanese for everything."

[vertexai]
vertex_project = "toshiclick"
vertex_location = ""
