services:
  # データベース系--------------------------------------------------
  n8n_db:
    container_name: n8n_db
    restart: always
    image: postgres:11
    env_file: ./.env.raspi
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - ./docker/n8n/db_data:/var/lib/postgresql/data
      - ./docker/n8n/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10
    tty: true
    stdin_open: true

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    env_file: ./.env.raspi
    ports:
      - 5678:5678
    links:
      - n8n_db
    volumes:
      - ./docker/n8n/data:/home/node/.n8n
    depends_on:
      n8n_db:
        condition: service_healthy
    tty: true
    stdin_open: true
