version: "2"
services:
  terraform:
    container_name: "terraform"
    build:
      context: ./docker/terraform
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: "1.1.1"
        TERRAGRUNT_VERSION: "0.35.16"
        TFLINT_VERSION: "0.34.0"
    env_file: ./.env
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
    tty: true

  ansible:
    container_name: "ansible"
    build:
      context: ./docker/ansible
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /ansible
    volumes:
      - ./ansible:/ansible
    tty: true

  nw-ansible:
    container_name: "nw-ansible"
    image: toshiclick/home_network_ansible_image:latest
    env_file: ./.env
    working_dir: /ansible
    volumes:
      - ./ansible:/ansible
    tty: true

  cloudformation:
    container_name: "cloudformation"
    build:
      context: ./docker/cloudformation
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /cloudformation
    volumes:
      - ./cloudformation:/cloudformation
    tty: true
