version: "2"
services:
  terraform:
    container_name: "terraform"
    build:
      context: ./docker/terraform
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: "1.1.1"
        TERRAGRUNT_VERSION: "0.35.16"
    env_file: ./.env
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
    tty: true
