---
wire_guard_server_ip_address: 172.16.101.1
wire_guard_server_listen_port: 51820
ufw_reset: yes
ufw_rules:
  - { from_ip: '127.0.0.0/8', comment: 'Allow localhost' }
  - { port: 22, rule: limit, comment: 'Allow Limit SSH' }
  - { port: 25, rule: allow, comment: 'Allow Mail' }
  - { port: 80, rule: allow, comment: 'Allow HTTP' }
  - { port: 443, rule: allow, comment: 'Allow HTTPS' }
  - { port: 51820, proto: udp, rule: allow, comment: 'wireguard' }
  - { from_ip: '172.16.0.0/12', port: 2049, rule: allow, comment: 'Allow NFS Server' }
  - { from_ip: '172.16.0.0/12', port: 33333, rule: allow, comment: 'Allow NFS static Mount port' }
  - { from_ip: '172.16.0.0/12', port: 6443, rule: allow, comment: 'Allow forward Kubelet' }
  - { port: 9100, rule: allow, comment: 'Allow Node Exporter' }
ufw_default_forward_policy: ACCEPT
ufw_logging: low
ufw_applications:
  - { name: "Postfix" }
github_runner_labels: [arm,linux,main]
