---
# stack名: terraform-user
AWSTemplateFormatVersion: "2010-09-09"
Description: "terraform-user"
Parameters:
  ProjectName:
    Type: String
    Default: toshi-terraform

Resources:
  TerraformIamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: terraform-iam-user

  TerraformIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: terraform-iam-group

  DenyIPIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: deny-ip-iam-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action:
              - "*"
            Resource:
              - "*"
            Condition:
              NotIpAddress:
                aws:SourceIp:
                  - 160.251.204.118/32
      Groups:
        - !Ref TerraformIamGroup

  TerraformIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: terraform-iam-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "*"
            Resource:
              - "*"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - 160.251.204.118/32
      Groups:
        - !Ref TerraformIamGroup

Outputs:
  ProjectName:
    Value: !Ref ProjectName
    Export:
      Name: ProjectName
