.lint_default: &lint_default
  stage: lint

variables:
  TERRAFORM_VERSION: 1.1.2
  # https://github.com/terraform-linters/tflint/releases/
  TFLINT_VERSION: 0.34.0

cfn-lint:
  <<: *lint_default
  image:
    name: python:3.10
  script:
    - pip install cfn-lint
    - cfn-lint --version
    - cfn-lint -t ./cloudformation/*.yml
  only:
    changes:
      - "cloudformation/**/*"
      - ".gitlab-ci.yml"

terraform-lint:
  <<: *lint_default
  image:
    name: hashicorp/terraform:${TERRAFORM_VERSION}
    entrypoint: [""]
  script:
    - cd terraform
    - wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip -O tflint.zip
    - unzip tflint.zip -d /bin
    - chmod 755 ./tflint.sh
    - ./tflint.sh
  only:
    changes:
      - "terraform/**/*"
      - ".gitlab-ci.yml"

ansiblelint:
  <<: *lint_default
  image: toshiclick/ci-ansible
  script:
    - cd ansible
    - ansible-lint all.yml -c .ansible-lint
  except:
    - schedules
  only:
    changes:
      - "ansible/**/*"
      - ".gitlab-ci.yml"

