.lint_default: &lint_default
  stage: lint

variables:
  TERRAFORM_VERSION: 1.1.2
  # https://github.com/terraform-linters/tflint/releases/
  TFLINT_VERSION: 0.34.0

cfn-lint:
  <<: *lint_default
  image:
    name: python:3.10
  script:
    - pip install cfn-lint
    - cfn-lint --version
    - cfn-lint -t ./cloudformation/*.yml
  only:
    changes:
      - "cloudformation/**/*"
      - ".gitlab-ci.yml"

terraform-lint:
  <<: *lint_default
  image:
    name: hashicorp/terraform:${TERRAFORM_VERSION}
    entrypoint: [""]
  before_script:
    - wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip -O tflint.zip
    - unzip tflint.zip -d /bin
    - rm tflint.zip
  script:
    - >-
      find . -type f -name "*.tf" -exec dirname {} \;
      | sort -u
      | while read line; do
          cd $line;
          echo "processing $PWD ..."
          terraform init -backend=false && tflint --config $CI_PROJECT_DIR/lint/.tflint.hcl;
          cd -;
        done
  only:
    changes:
      - "terraform/**/*"
      - ".gitlab-ci.yml"

ansiblelint:
  <<: *lint_default
  image: toshiclick/ci-ansible
  script:
    - ansible-lint all.yml -c .ansible-lint
  except:
    - schedules
  only:
    changes:
      - "ansible/**/*"
      - ".gitlab-ci.yml"

ansible_syntax:
  <<: *lint_default
  script:
    - ansible-playbook -i hosts_all.yml all.yml --syntax-check --vault-password-file ~/.ssh/.ansible_vault_pass -C
  only:
    # 実行されるブランチを指定(vault passはプロテクトブランチでしか取れないようにしているので。)
    refs:
      - main
    changes:
      - "ansible/**/*"
      - ".gitlab-ci.yml"
  except:
    - schedules
