ufw_reset: yes
ufw_rules:
  - { from_ip: '127.0.0.0/8', comment: 'Allow localhost' }
  - { port: 22, rule: limit, comment: 'Allow Limit SSH' }
  - { port: 25, rule: allow, comment: 'Allow Mail' }
  - { port: 80, rule: allow, comment: 'Allow HTTP' }
  - { port: 443, rule: allow, comment: 'Allow HTTPS' }
  - { port: 9100, rule: allow, comment: 'Allow Node Exporter' }
  - { from_ip: '172.16.0.0/12', port: 3389, rule: allow, comment: 'Allow XRDP' }
  - { from_ip: '172.16.0.0/12', port: 139, rule: allow, comment: 'Allow Samba' }
  - { from_ip: '172.16.0.0/12', port: 445, rule: allow, comment: 'Allow Samba' }
ufw_default_forward_policy: ACCEPT
ufw_logging: low
ufw_applications:
  - { name: "Postfix" }
