---
hostname: L3Switch
domain_name: l3switch.test
interfaces:
  - ios_if: "GigabitEthernet0/9"
    desc: "To Internet_Router"
    enabled: true
    ipv4: "172.16.1.2/16"
  - ios_if: "GigabitEthernet0/1"
    desc: "To L2SW VLAN Bridge"
    enabled: true
    mode: trunk
    native_vlan: 99
    allowed_vlans: 1,99,77,100,177
  - ios_if: "GigabitEthernet0/2"
    desc: "access port"
    enabled: true
    mode: access
    vlan_id: 100
#    ipv4: "10.100.101.253/24"
#    ipv6: "2001:db8:101::f/64"
  - ios_if: "GigabitEthernet0/3"
    desc: "access port"
    enabled: true
    mode: access
    vlan_id: 100
  #    ipv4: "dhcp"
  #    ipv6: "2001:db8:901:beef::1/128"
  - ios_if: "GigabitEthernet0/4"
    desc: "access port"
    enabled: true
    mode: access
    vlan_id: 100
#    ipv4: "10.100.201.254/24"
#    ipv6: "2001:db8:201::a/64"
  - ios_if: "GigabitEthernet0/5"
    desc: "access port"
    enabled: true
    mode: access
    vlan_id: 100
  - ios_if: "GigabitEthernet0/6"
    desc: "trunk port"
    enabled: true
    mode: trunk
    native_vlan: 177
    allowed_vlans: 1,99,77,100,177
  - ios_if: "GigabitEthernet0/7"
    desc: "trunk port"
    enabled: true
    mode: trunk
    native_vlan: 177
    allowed_vlans: 1,99,77,100,177
  - ios_if: "GigabitEthernet0/8"
    desc: "trunk port"
    enabled: true
    mode: trunk
    native_vlan: 99
    allowed_vlans: 1,99,77,100,177
