# Slackチャンネルの情報
slack_channel: "home_server"
slack_icon: ":house:"
spin_out_hdd_list:
  - { name: /dev/sda }
  - { name: /dev/sdb }
  - { name: /dev/sdc }
  - { name: /dev/sdd }

mackerel_install: true
cron_setting: true
package_control_auto_reboot: false

rkhunter_install: true
rkhunter_script_whitelist:
  - /usr/bin/which
  - /bin/egrep
  - /bin/fgrep
  - /usr/bin/egrep
  - /usr/bin/fgrep
  - /bin/which
  - /usr/bin/ldd
  - /usr/sbin/adduser

# https://github.com/weareinteractive/ansible-ufw
ufw_reset: yes
ufw_rules:
  - { from_ip: '127.0.0.0/8', rule: allow, comment: 'Allow localhost' }
  - { port: 22, rule: limit, comment: 'Allow Limit SSH' }
  - { port: 25, rule: allow, comment: 'Allow Mail' }
  - { port: 80, rule: allow, comment: 'Allow HTTP' }
  - { port: 443, rule: allow, comment: 'Allow HTTPS' }
  - { port: 9100, rule: allow, comment: 'Allow Node Exporter' }
  - { port: 24224, rule: allow, comment: 'Allow Fluentd' }
  - { from_ip: '172.16.0.0/12', port: 3389, rule: allow, comment: 'Allow XRDP' }
  - { from_ip: '172.16.0.0/12', port: 139, rule: allow, comment: 'Allow Samba' }
  - { from_ip: '172.16.0.0/12', port: 445, rule: allow, comment: 'Allow Samba' }
#  - { port: 6443, rule: allow, comment: 'Allow Kubelet' }
#  - { from_ip: '172.16.0.0/16', port: "2379:2380", proto: tcp, rule: allow, comment: 'Kubernetes Master' }
#  - { from_ip: '172.16.0.0/16', port: "10250:10252", proto: tcp, rule: allow, comment: 'Kubernetes Master' }
ufw_default_forward_policy: ACCEPT
ufw_logging: low
ufw_applications:
  - { name: "Postfix" }
