# CI Lint tool
# https://gitlab.com/toshi_click/server/ansible_for_server/-/ci/lint
---
stages:
  - lint
  - deploy

include:
  - local: '/cicd/.gitlab-ci-lint-template.yml'
  - local: '/cicd/.gitlab-ci-deploy-template.yml'

variables:
  # サブモジュールを更新する場合にはこれを有効にする
  GIT_SUBMODULE_STRATEGY: recursive
  # to avoid this problem:
  # UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 140: ordinal not in range(128)
  LANG: ja_JP.UTF-8

cache:
  # ジョブ毎にキャッシュを共有する設定
  key: "$CI_JOB_NAME"
  untracked: true
