.lint_default: &lint_default
  stage: lint

variables:
  TERRAFORM_VERSION: 1.1.2
  # https://github.com/terraform-linters/tflint/releases/
  TFLINT_VERSION: 0.34.0

terraform-lint:
  <<: *lint_default
  image:
    name: hashicorp/terraform:${TERRAFORM_VERSION}
    entrypoint: [""]
  script:
    - cd terraform
    - wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip -O tflint.zip
    - unzip tflint.zip -d -d /usr/local/bin
    - chmod 755 ./tflint.sh
    - sh -x ./tflint.sh
  except:
    - schedules
  only:
    changes:
      - "terraform/**/*"
      - ".gitlab-ci.yml"

ansiblelint:
  <<: *lint_default
  image: toshiclick/ci-ansible
  script:
    - cd ansible
    - ansible-lint --version
    - ansible-galaxy collection install -r requirements.yml --force-with-deps
    - ansible-galaxy install -p roles -r requirements.yml --force
    - ansible-lint all.yml -c .ansible-lint
  except:
    - schedules
  only:
    changes:
      - "ansible/**/*"
      - ".gitlab-ci.yml"
