---
- block:
#    - name: debug github_runner_labels
#      ansible.builtin.debug:
#        msg: "{{ github_runner_labels }}"
#      when: github_runner_labels is defined

    - name: Set complete API url for repo runner
      ansible.builtin.set_fact:
        github_full_api_url: "https://api.github.com/repos/{{ github_account }}/{{ github_repo }}/actions/runners"
      when: not github_runner_org

    - name: Set complete API url for org runner
      ansible.builtin.set_fact:
        github_full_api_url: "https://api.github.com/orgs/{{ github_org_name }}/actions/runners"
      when: github_runner_org | bool

    - name: Set runner install dir
      ansible.builtin.set_fact:
        github_runner_dir: "{{ github_runner_dir_base }}/{{ github_runner_dir_name }}"

    - name: Get registration token
      ansible.builtin.uri:
        url: "{{ github_full_api_url }}/registration-token"
        headers:
          Authorization: "token {{ github_access_token }}"
          Accept: "application/vnd.github.v3+json"
        method: POST
        status_code: 201
        force_basic_auth: yes
      register: registration

    - name: Check currently registered runners for repo
      ansible.builtin.uri:
        url: "{{ github_full_api_url }}"
        headers:
          Authorization: "token {{ github_access_token }}"
          Accept: "application/vnd.github.v3+json"
        method: GET
        status_code: 200
        force_basic_auth: yes
      register: registered_runners

#    - name: debug registered_runners
#      ansible.builtin.debug:
#        msg: "{{ registered_runners }}"
#      when: registered_runners is defined

    - name: Check service facts
      ansible.builtin.service_facts:

  check_mode: false
