---
- name: Check if runner service name file exist
  ansible.builtin.stat:
    path: "{{ github_runner_dir }}/.service"
  register: runner_service_file_path

- name: Uninstall runner
  ansible.builtin.command: "./svc.sh uninstall"
  args:
    chdir: "{{ github_runner_dir }}"
  become: true
  when: runner_service_file_path.stat.exists

- name: Check GitHub Actions runner file
  ansible.builtin.stat:
    path: "{{ github_runner_dir }}/.runner"
  register: runner_file

- name: Unregister runner from the GitHub
  environment:
    RUNNER_ALLOW_RUNASROOT: "1"
  ansible.builtin.command: "./config.sh remove --token {{ registration.json.token }} --name '{{ github_runner_name }}' --unattended"
  args:
    chdir: "{{ github_runner_dir }}"
  become: true
  become_user: "{{ manage_user_name }}"
  no_log: yes
  when: github_runner_name in registered_runners.json.runners|map(attribute='name')|list and runner_file.stat.exists

- name: Delete runner directory
  ansible.builtin.file:
    path: "{{ github_runner_dir }}"
    state: absent
