---
- name: bere metal setting
  hosts:
    - bare_metal
  become: true
  become_user: root
  ignore_unreachable: true
  roles:
    - { role: "samba", when: server_group == "shigure" or server_group == "mayu" }
    - { role: "kvm" }
  tasks:
    # HDDのスピンアウトを設定して省電力化のためのsmartツールをインストールする
    # https://www.systemworks.co.jp/ex_spindown.php
    - name: Install smartmontools
      ansible.builtin.package:
        name:
          - smartmontools
        state: present

    - name: /etc/smartd.conf set
      template:
        src: "etc/smartd.conf"
        dest: "/etc/smartd.conf"
        owner: root
        group: root
        mode: 0644
        backup: true

    - block:
        - name: systemd set state nmbd
          service:
            name: nmbd
            state: restarted
            enabled: yes

        - name: systemd set state samba
          service:
            name: smbd
            state: restarted
            enabled: yes
      when:
        - server_group == "shigure" or server_group == "mayu"
