- hosts: dns
  become: true
  become_user: root
  ignore_unreachable: yes
  tasks:
    # namedのためにsystemd-resolvedを設定変更する
    # https://qiita.com/shora_kujira16/items/31d09b373809a5a44ae5
    - name: Create symbolic link resolv.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: put /etc/systemd/resolved.conf
      template:
        src: etc/systemd/resolved.conf
        dest: "/etc/systemd/resolved.conf"

    - name: systemd set state systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
        enabled: yes

    - name: "/var/log/named directory create"
      file:
        path: "/var/log/named"
        state: directory
        owner: root
        group: root
        mode: 0777
    - name: "/var/log/named log file create"
      file:
        path: "/var/log/named/{{ item }}"
        state: touch
        owner: root
        group: root
        mode: 0666
      with_items:
        - named.log
        - security.log
        - queries.log
