all:
  vars:
    ansible_ssh_user: toshi
    ansible_ssh_port: 22
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ignore_unreachable: yes
  children:
    toshi:
      hosts:
        toshi.click: { }
    shigure:
      hosts:
        shigure.test: { }
    mayu:
      hosts:
        mayu.test: { }
    ranko:
      hosts:
        ranko.test: { }
    dns:
      hosts:
        dns.test: { }
    raspi:
      hosts:
        raspi.test: { }
#      children:
#        raspi_master: { }
#        raspi_worker: { }
#    raspi_master:
#      hosts:
#        raspi-master.test: { }
#    raspi_worker:
#      hosts:
#        raspi-worker1.test: { }
#        raspi-worker2.test: { }
#        raspi-worker3.test: { }
    bare_metal:
      children:
        shigure: { }
        mayu: { }
        ranko: { }
    vm:
      children:
        dns: { }
    # YAMAHA RTX1210
    router:
      children:
        hosts:
          172.16.1.1: {}
    # Cisco WS-C3560CG-8PC-S
    l3:
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_user: admin
        ansible_become: yes
        ansible_become_method: enable
      children:
        l3switch:
          hosts:
            172.28.1.1: {}
    # Cisco WS-C2960CG-8TC-L
    l2:
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_user: admin
        ansible_become: yes
        ansible_become_method: enable
      children:
        l2switch:
          hosts:
            172.28.1.2: {}
