all:
  children:
    linux:
      vars:
        ignore_unreachable: yes
        ansible_ssh_user: toshi
        ansible_ssh_port: 22
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
      children:
        shigure:
          hosts:
            shigure.test: { }
        mayu:
          hosts:
            mayu.test: { }
        dev:
          hosts:
            dev.test:
              ansible_connection: local
        raspi:
          vars:
            github_runner_labels: [arm,linux]
          hosts:
            raspi.test: { }
            rasdev.test: { }
            ranko.test: { }
            sae.test: {}
            kaede.test: {}
            shiki.test: {}
        bare_metal:
          children:
            shigure: { }
            mayu: { }
        vm:
          children:
            dev: { }
    network_switch:
      children:
        # YAMAHA RTX1210
        router:
          hosts:
            172.16.1.1: {}
        cisco:
          vars:
            ansible_connection: network_cli
            ansible_network_os: ios
            ansible_ssh_user: admin
            ansible_become: yes
            ansible_become_method: enable
          children:
            # Cisco WS-C3560CG-8PC-S
            l3switch:
              hosts:
                172.28.1.1: {}
            # Cisco WS-C2960CG-8TC-L
            l2switch:
              hosts:
                172.28.1.2: { }
