---
- name: backup router configurations
  hosts: routers
  connection: network_cli
  gather_facts: no
  ignore_unreachable: true
  tasks:
    - name: gather ios_facts
      ios_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: Backup configuration
      ios_config:
        backup: yes
