---
- name: linux setting
  hosts: linux
  become: true
  become_user: root
  gather_facts: yes
  ignore_unreachable: true
  tasks:
    - name: Add to docker group
      user:
        name: "{{ manage_user_name }}"
        groups: docker
        append: yes

    - name: "git safe directory at /home/{{ manage_user_name }}/scripts"
      shell: "git config --global --add safe.directory /home/{{ manage_user_name }}/scripts"

    - name: Check if scripts directory exists
      stat:
        path: "/home/{{ manage_user_name }}/scripts"
      register: scripts_dir_stat

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ manage_user_name }}/scripts"
        state: directory
        owner: "{{ manage_user_name }}"
        group: "{{ manage_user_group }}"
        recurse: yes
      when: scripts_dir_stat.stat.exists

    - name: Clone scripts github repository
      become: yes
      become_user: '{{ manage_user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/scripts.git
        dest: "/home/{{ manage_user_name }}/scripts"
        clone: yes
        update: yes
        key_file: "/home/{{ manage_user_name }}/.ssh/gitkey"
        accept_hostkey: true

    - name: "git safe directory at /home/{{ manage_user_name }}/scripts"
      shell: "git config --global --add safe.directory /home/{{ manage_user_name }}/infra"

    - name: Check if infra directory exists
      stat:
        path: "/home/{{ manage_user_name }}/infra"
      register: infra_dir_stat

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ manage_user_name }}/infra"
        state: directory
        owner: "{{ manage_user_name }}"
        group: "{{ manage_user_group }}"
        recurse: yes
      when: infra_dir_stat.stat.exists

    - name: Clone infra github repository
      become: yes
      become_user: '{{ manage_user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/infra.git
        dest: "/home/{{ manage_user_name }}/infra"
        clone: yes
        update: yes
        key_file: "/home/{{ manage_user_name }}/.ssh/gitkey"
        accept_hostkey: true

    - name: Install wireguard client
      ansible.builtin.package:
        name:
          - wireguard
        state: present

    - name: Install resolvconf
      ansible.builtin.package:
        name:
          - resolvconf
        state: present

    - name: /etc/systemd/resolved.conf set
      template:
        src: "etc/systemd/resolved.conf"
        dest: /etc/systemd/resolved.conf
        owner: root
        group: root
        mode: 0644

    - name: restart resolvconf
      service:
        name: resolvconf
        state: restarted
        enabled: yes

    - name: restart resolvconf
      service:
        name: systemd-resolved
        state: restarted
        enabled: yes

    - name: Generate /etc/hosts file
      template:
        src: "etc/hosts"
        dest: "/etc/hosts"
        owner: root
        group: root
        mode: 0644
        backup: true

    - name: Install debug tools
      ansible.builtin.package:
        name:
          - procps
          - util-linux
          - sysstat
          - iproute2
          - numactl
          - tcpdump
          - linux-tools-common
          - bcc
          - bpfcc-tools
          - bpftrace
          - trace-cmd
          - nicstat
          - ethtool
          - tiptop
        state: present

    - name: apt add golang repository
      ansible.builtin.apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: Install golang
      ansible.builtin.package:
        name:
          - golang
          - golang-go
        state: present

    - name: Install nodejs and npm
      ansible.builtin.package:
        name:
          - nodejs
          - npm
        state: present

    - name: npmでgo-task/cliをグローバルインストール
      npm:
        name: "@go-task/cli"
        global: yes
        state: present
