---
- hosts: linux
  become: true
  become_user: root
  gather_facts: yes
  tasks:
    - name: Add to docker group
      user:
        name: "{{ manage_user_name }}"
        groups: docker
        append: yes

    - name: Clone scripts github repository
      git:
        repo: git@github.com:toshibe678/scripts.git
        dest: "/home/{{ manage_user_name }}/scripts"
        clone: yes
        update: yes
        key_file: "/home/{{ manage_user_name }}/.ssh/gitkey"
        accept_hostkey: true
