---
- name: linux setting
  hosts: linux
  become: true
  become_user: root
  gather_facts: yes
  ignore_unreachable: true
  tasks:
    - name: Add to docker group
      user:
        name: "{{ manage_user_name }}"
        groups: docker
        append: yes

    - name: Clone scripts github repository
      become: yes
      become_user: '{{ manage_user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/scripts.git
        dest: "/home/{{ manage_user_name }}/scripts"
        clone: yes
        update: yes
        key_file: "/home/{{ manage_user_name }}/.ssh/gitkey"
        accept_hostkey: true

    - name: Clone infra github repository
      become: yes
      become_user: '{{ manage_user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/infra.git
        dest: "/home/{{ manage_user_name }}/infra"
        clone: yes
        update: yes
        key_file: "/home/{{ manage_user_name }}/.ssh/gitkey"
        accept_hostkey: true

    - name: Install wireguard client
      ansible.builtin.package:
        name:
          - wireguard-tools
        state: present
