- hosts:
    - linux
  become: true
  become_user: root
  ignore_unreachable: yes
  tasks:
    - name: "set mackerel conf"
      template:
        src: "mackerel-agent.conf.j2"
        dest: "/etc/mackerel-agent/mackerel-agent.conf"
        owner: root
        group: root
        mode: 0644
      when: mackerel_install

    - name: systemd set state mackerel-agent
      service:
        name: mackerel-agent
        state: restarted
        enabled: yes
      when: mackerel_install
