- hosts: linux
  become: true
  become_user: root
  ignore_unreachable: yes
  roles:
    - { role: "rootkit_hunter", when: rkhunter_install}
  tasks:
    - name: put rkhunter local setting file
      template:
        src: etc/rkhunter.conf.local
        dest: /etc/rkhunter.conf.local
        owner: root
        group: root
        mode: 0644
      when: rkhunter_install

    - name: "rkhunter --propupd"
      command: rkhunter --propupd
      when: rkhunter_install
