---
- name: yamaha router setting
  hosts: router
  vars:
    ansible_network_os: yamaha_network.rtx.rtx
    ansible_connection: network_cli
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
  tasks:
    # 文字化けするときは > console character ja.utf8
    # 上やってもエンコードの問題で手元で動かないのでコメントアウト
#    - name: get configuration
#      yamaha_network.rtx.rtx_config:
#        backup: yes
#        backup_options:
#          filename: backup.txt

#    - name: show environment
#      yamaha_network.rtx.rtx_command:
#        commands: show environment
#      register: environment_result
#
#    - name: show environment
#      debug:
#        msg: "{{ environment_result.stdout_lines[0] }}"

    - name: get configuration
      yamaha_network.rtx.rtx_command:
        commands:
          - show config
      register: result

    - name: show config
      debug:
        msg: "{{ result.stdout_lines[0] }}"

    - name: set DNS common setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dns service recursive
#          - dns private router.test
          - dns domain test
          - dns host 172.16.0.0-172.31.254.254
          - dns cache use on
          - dns cache max entry 1024
        save_when: changed

    # ip host コマンドは、dns static コマンドで a と ptr を両方設定することを簡略化したものである。
    # ip host pc1.rtpro.yamaha.co.jp 133.176.200.1
    # dns static ptr 133.176.200.2 pc2.yamaha.co.jp
    # dns static cname mail.yamaha.co.jp mail2.yamaha.co.jp
    - name: set DNS hosts setting
      yamaha_network.rtx.rtx_config:
        lines:
#          - ip host shigure.test 172.28.177.100
#          - ip host mayu.test 172.28.177.200
#          - ip host ranko.test 172.28.100.64
          - ip host raspi.test 172.16.100.254
          - ip host raspi-master.test 172.16.100.131
          - ip host raspi-worker1.test 172.16.100.132
          - ip host raspi-worker2.test 172.16.100.133
          - ip host raspi-worker3.test 172.16.100.134
          - ip host router.test 172.16.1.1
          - ip host wifi 172.16.254.101
          - ip host l3-3560 172.28.1.1
          - ip host l2-2960 172.28.1.2
          - ip host printer 172.16.177.211
          - ip host ip-phone 172.16.177.210
          - ip host vpnclient 172.16.77.201
          - ip host qnap 172.16.100.241
          - ip host qnap2 172.16.100.242
#          - ip host qnap-bak1 172.28.100.241
#          - ip host qnap-bak2 172.28.100.242
          - ip host toshipc01 172.16.77.11
          - ip host toshipc02 172.16.77.21
        save_when: changed

    # DHCP
    - name: set DHCP setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dhcp service server
          - dhcp server rfc2131 compliant except remain-silent
          - dhcp scope 1 172.16.2.2-172.16.254.254/16
          - dhcp scope bind 1 172.16.11.10 ethernet C8:7F:54:0A:75:21
          - dhcp scope bind 1 172.16.77.21 ethernet b0:a4:60:c2:ce:05
          - dhcp scope bind 1 172.16.100.12 ethernet 34:de:1a:59:1f:32
          - dhcp scope bind 1 172.16.100.71 ethernet 00:25:22:a0:b0:4c
          - dhcp scope bind 1 172.16.100.106 ethernet 8c:25:05:db:3a:20
          - dhcp scope bind 1 172.16.100.107 ethernet 0c:9d:92:71:0c:bd
          - dhcp scope bind 1 172.16.100.108 ethernet dc:72:9b:c7:23:9f
          - dhcp scope bind 1 172.16.100.109 ethernet 1c:fe:2b:10:0d:8f
          - dhcp scope bind 1 172.16.100.110 ethernet 98:41:5c:e3:1b:fc
          - dhcp scope bind 1 172.16.100.131 ethernet dc:a6:32:91:b1:9a
          - dhcp scope bind 1 172.16.100.205 ethernet 58:cb:52:7d:dc:a2
          - dhcp scope bind 1 172.16.100.210 ethernet 00:0b:82:91:bf:db
          - dhcp scope bind 1 172.16.100.211 ethernet f4:a9:97:48:c2:a2
          - dhcp scope bind 1 172.16.100.241 ethernet 24:5e:be:1f:34:c8
          - dhcp scope bind 1 172.16.100.251 ethernet f4:69:42:17:4c:1a
        save_when: changed


#    - name: set description
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - description 1 yamaha

#    - name: set lan2
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - ip lan2 address dhcp
#
#    - name: set lan3
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - pp always-on on
#          - pppoe use lan3
#        parents:
#          - pp select 1
#        match: strict
#        save_when: changed

    - name: get configuration
      yamaha_network.rtx.rtx_command:
        commands:
          - show config
      register: result

    - name: show config
      debug:
        msg: "{{ result.stdout_lines[0] }}"
