---
- name: yamaha router setting
  hosts: router
  ignore_unreachable: true
  vars:
    ansible_network_os: yamaha_network.rtx.rtx
    ansible_connection: network_cli
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
  tasks:
    # 文字化けするときは > console character ja.utf8
    # 上やってもエンコードの問題で手元で動かないのでコメントアウト
#    - name: get configuration
#      yamaha_network.rtx.rtx_config:
#        backup: yes
#        backup_options:
#          filename: backup.txt

#    - name: show environment
#      yamaha_network.rtx.rtx_command:
#        commands: show environment
#      register: environment_result
#
#    - name: show environment
#      debug:
#        msg: "{{ environment_result.stdout_lines[0] }}"

    - name: set DNS common setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dns service recursive
#          - dns private router.test
          - dns domain test
          - dns host 172.16.0.0-172.31.254.254
          - dns cache use on
          - dns cache max entry 1024
        save_when: changed

    # ip host コマンドは、dns static コマンドで a と ptr を両方設定することを簡略化したものである。
    # ip host pc1.rtpro.yamaha.co.jp 133.176.200.1
    # dns static ptr 133.176.200.2 pc2.yamaha.co.jp
    # dns static cname mail.yamaha.co.jp mail2.yamaha.co.jp
    - name: set DNS hosts setting
      yamaha_network.rtx.rtx_config:
        lines:
          - ip host raspi.test 172.16.100.254
          - ip host rasdev.test 172.16.100.253
          - ip host router.test 172.16.1.1
          - ip host wifi 172.16.254.101
        save_when: changed

    # DHCP
    - name: set DHCP setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dhcp service server
          - dhcp server rfc2131 compliant except remain-silent
          - dhcp scope 1 172.16.2.2-172.16.254.254/16
          - dhcp scope bind 1 172.16.100.205 ethernet 58:cb:52:7d:dc:a2
          - dhcp scope bind 1 172.16.100.210 ethernet 00:0b:82:91:bf:db
          - dhcp scope bind 1 172.16.100.211 ethernet f4:a9:97:48:c2:a2
          - dhcp scope bind 1 172.16.100.241 ethernet 24:5e:be:1f:34:c8
          - dhcp scope bind 1 172.16.100.251 ethernet f4:69:42:17:4c:1a
          # shigure
          #
          # mayu
          - dhcp scope bind 1 172.16.77.200 ethernet bc:5f:f4:d8:4a:cc
        save_when: changed


#    - name: set description
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - description 1 yamaha

#    - name: set lan2
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - ip lan2 address dhcp
#
#    - name: set lan3
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - pp always-on on
#          - pppoe use lan3
#        parents:
#          - pp select 1
#        match: strict
#        save_when: changed
