---
- name: yamaha router setting
  hosts: router
  ignore_unreachable: true
  vars:
    ansible_network_os: yamaha_network.rtx.rtx
    ansible_connection: network_cli
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
  tasks:
    # 文字化けするときは > console character ja.utf8
    # 上やってもエンコードの問題で手元で動かないのでコメントアウト
#    - name: get configuration
#      yamaha_network.rtx.rtx_config:
#        backup: yes
#        backup_options:
#          filename: backup.txt

#    - name: show environment
#      yamaha_network.rtx.rtx_command:
#        commands: show environment
#      register: environment_result
#
#    - name: show environment
#      debug:
#        msg: "{{ environment_result.stdout_lines[0] }}"

    - name: set DNS common setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dns service recursive
#          - dns private router.test
          - dns domain test
          - dns host 172.16.0.0-172.31.254.254
          - dns cache use on
          - dns cache max entry 1024
        save_when: changed

    # ip host コマンドは、dns static コマンドで a と ptr を両方設定することを簡略化したものである。
    # ip host pc1.rtpro.yamaha.co.jp 133.176.200.1
    # dns static ptr 133.176.200.2 pc2.yamaha.co.jp
    # dns static cname mail.yamaha.co.jp mail2.yamaha.co.jp
    - name: set DNS hosts setting
      yamaha_network.rtx.rtx_config:
        lines:
          - ip host raspi.test 172.16.100.254
          - ip host rasdev.test 172.16.100.253
          - ip host router.test 172.16.1.1
          - ip host wifi 172.16.254.101
        save_when: changed

    # DHCP
    - name: set DHCP setting
      yamaha_network.rtx.rtx_config:
        lines:
          - dhcp service server
          - dhcp server rfc2131 compliant except remain-silent
          - dhcp scope 1 172.16.2.2-172.16.254.254/16
          # shigure
          - dhcp scope bind 1 172.16.77.100 ethernet 00:d8:61:a1:51:9b
          # mayu
          - dhcp scope bind 1 172.16.77.200 ethernet bc:5f:f4:d8:4a:cc
          # QNAP
          - dhcp scope bind 1 172.16.100.241 ethernet 24:5E:BE:04:9A:F8
          - dhcp scope bind 1 172.16.100.242 ethernet 24:5E:BE:04:9A:F9
          # QNAP TS-231P
          - dhcp scope bind 1 172.16.100.243 ethernet 24:5e:be:1f:34:c8
          - dhcp scope bind 1 172.16.100.244 ethernet 24:5e:be:1f:34:c9
          # tepra
          - dhcp scope bind 1 172.16.100.245 ethernet b0:e8:92:a3:01:1d
          # pixel4a
          - dhcp scope bind 1 172.16.250.2 ethernet e2:3c:3d:2d:cb:b5
          # pixel6
          - dhcp scope bind 1 172.16.250.3 ethernet 0c:c4:13:1d:69:4d
          # pixel6a
          - dhcp scope bind 1 172.16.250.4 ethernet 2e:28:4f:fd:b9:95
          # yukari pc
          - dhcp scope bind 1 172.16.250.5 ethernet 70:85:c2:40:d2:0b
          # yukari ROG-Phone-5
          - dhcp scope bind 1 172.16.250.6 ethernet 8e:4a:fc:c8:ac:1a
          # amazon-Fire TV Stick 4k max
          - dhcp scope bind 1 172.16.250.7 ethernet 10:ce:02:7f:90:76
          # fujie pc
          - dhcp scope bind 1 172.16.250.8 ethernet 28:cd:c4:c5:86:2f
          # firetablet 10 hd
          - dhcp scope bind 1 172.16.250.9 ethernet 1c:93:c4:72:59:4c
          # switch
          - dhcp scope bind 1 172.16.250.10 ethernet bc:ce:25:f9:ad:78
          # amazon-Fire TV Stick 4k
          - dhcp scope bind 1 172.16.250.11 ethernet 1c:fe:2b:10:0d:8f
          # Pixel-3-XL
          - dhcp scope bind 1 172.16.250.11 ethernet b2:a0:91:3b:64:45

        save_when: changed

#    - name: set description
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - description 1 yamaha

#    - name: set lan2
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - ip lan2 address dhcp
#
#    - name: set lan3
#      yamaha_network.rtx.rtx_config:
#        lines:
#          - pp always-on on
#          - pppoe use lan3
#        parents:
#          - pp select 1
#        match: strict
#        save_when: changed
