server_group: "vpn"

ufw_reset: yes
ufw_rules:
  - { from_ip: '127.0.0.0/8', comment: 'Allow localhost' }
  - { port: 22, rule: limit, comment: 'Allow Limit SSH' }
  - { port: 25, rule: allow, comment: 'Allow Mail' }
  - { port: 80, rule: allow, comment: 'Allow HTTP' }
  - { port: 443, rule: allow, comment: 'Allow HTTPS' }
  - { port: 51820, proto: udp, rule: allow, comment: 'wireguard' }
  - { port: 9100, rule: allow, comment: 'Allow Node Exporter' }
ufw_default_forward_policy: ACCEPT
ufw_logging: low
ufw_applications:
  - { name: "Postfix" }

wire_guard_server_host: "{{ crypt_wire_guard_server_host }}"
wire_guard_server_listen_port: 51820
wire_guard_server_ip_address: "{{ crypt_wire_guard_server_ip_address }}"
wire_guard_server_wan_interface: eth0
