server_group: "vpn"

ufw_reset: yes
ufw_rules:
  - { from_ip: '127.0.0.0/8', comment: 'Allow localhost' }
  - { port: 22, rule: limit, comment: 'Allow Limit SSH' }
  - { port: 25, rule: allow, comment: 'Allow Mail' }
  - { port: 80, rule: allow, comment: 'Allow HTTP' }
  - { port: 443, rule: allow, comment: 'Allow HTTPS' }
  - { port: 51820, proto: udp, rule: allow, comment: 'wireguard' }
  - { port: 9100, rule: allow, comment: 'Allow Node Exporter' }
ufw_default_forward_policy: ACCEPT
ufw_logging: low
ufw_applications:
  - { name: "Postfix" }

wire_guard_server_host: "{{ crypt_wire_guard_server_host }}"
wire_guard_server_listen_port: 51820
wire_guard_server_ip_address: "{{ crypt_wire_guard_server_ip_address }}"
wire_guard_server_private_key: "{{ crypt_wire_guard_server_private_key }}"
wire_guard_server_public_key: M0WSPoqUVs1OBAXhBYr/MtQE8AhQoLlwSAW+FL5RZGk=
wire_guard_server_wan_interface: eth0
wire_guard_clients:
  - name: toshipc01
    private_key: "{{ crypt_wire_guard_client_toshipc01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc01_preshared_key }}"
    ip_address: 172.16.101.10
    forward_address: 172.16.101.0/24
  - name: toshipc02
    private_key: "{{ crypt_wire_guard_client_toshipc02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_toshipc02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_toshipc02_preshared_key }}"
    ip_address: 172.16.101.11
    forward_address: 172.16.101.0/24
  - name: smartphone01
    private_key: "{{ crypt_wire_guard_client_smartphone01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone01_preshared_key }}"
    ip_address: 172.16.101.21
    forward_address: 0.0.0.0/0
  - name: smartphone02
    private_key: "{{ crypt_wire_guard_client_smartphone02_private_key }}"
    public_key: "{{ crypt_wire_guard_client_smartphone02_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_smartphone02_preshared_key }}"
    ip_address: 172.16.101.22
    forward_address: 0.0.0.0/0
  - name: other01
    private_key: "{{ crypt_wire_guard_client_other01_private_key }}"
    public_key: "{{ crypt_wire_guard_client_other01_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_other01_preshared_key }}"
    ip_address: 172.16.101.99
    forward_address: 0.0.0.0/0
  - name: shigure
    private_key: "{{ crypt_wire_guard_client_shigure_private_key }}"
    public_key: "{{ crypt_wire_guard_client_shigure_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_shigure_preshared_key }}"
    ip_address: 172.16.101.71
    forward_address: 172.16.101.0/24
  - name: mayu
    private_key: "{{ crypt_wire_guard_client_mayu_private_key }}"
    public_key: "{{ crypt_wire_guard_client_mayu_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_mayu_preshared_key }}"
    ip_address: 172.16.101.72
    forward_address: 172.16.101.0/24
  - name: ranko
    private_key: "{{ crypt_wire_guard_client_ranko_private_key }}"
    public_key: "{{ crypt_wire_guard_client_ranko_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_ranko_preshared_key }}"
    ip_address: 172.16.101.73
    forward_address: 172.16.101.0/24
  - name: qnapmain
    private_key: "{{ crypt_wire_guard_client_qnapmain_private_key }}"
    public_key: "{{ crypt_wire_guard_client_qnapmain_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_qnapmain_preshared_key }}"
    ip_address: 172.16.101.91
    forward_address: 172.16.101.0/24
  - name: qnapsub
    private_key: "{{ crypt_wire_guard_client_qnapsub_private_key }}"
    public_key: "{{ crypt_wire_guard_client_qnapsub_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_qnapsub_preshared_key }}"
    ip_address: 172.16.101.92
    forward_address: 172.16.101.0/24
  - name: mother
    private_key: "{{ crypt_wire_guard_client_mother_private_key }}"
    public_key: "{{ crypt_wire_guard_client_mother_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_mother_preshared_key }}"
    ip_address: 172.16.101.201
    forward_address: 172.16.101.0/24
  - name: sister1
    private_key: "{{ crypt_wire_guard_client_sister1_private_key }}"
    public_key: "{{ crypt_wire_guard_client_sister1_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_sister1_preshared_key }}"
    ip_address: 172.16.101.202
    forward_address: 172.16.101.0/24
  - name: sister2
    private_key: "{{ crypt_wire_guard_client_sister2_private_key }}"
    public_key: "{{ crypt_wire_guard_client_sister2_public_key }}"
    preshared_key: "{{ crypt_wire_guard_client_sister2_preshared_key }}"
    ip_address: 172.16.101.203
    forward_address: 172.16.101.0/24
