name: Lint Ansible Templates

on:
  push:
    paths:
      - "ansible/**"

jobs:
  ansible-lint:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ansible Linter with Latest Version
        uses: ansible/ansible-lint-action@main

      - name: Print the ansible lint Linter Version & run Linter.
        run: |
          cd ansible

          ansible-lint --version
          ansible-lint all.yml -c .ansible-lint
