name: Lint Ansible Templates

on:
  push:
    paths:
      - "ansible/**"
    branches:
      - main
      - develop
      - 'releases/**'

jobs:
  ansible-lint:
    runs-on: self-hosted
    container:
      image: ghcr.io/toshibe678/infra/ansible
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print the ansible lint Linter Version & run Linter.
        env:
          TOSHI_KEY: ${{ secrets.TOSHI_KEY }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          cd ansible
          ansible-lint --version
          ansible-galaxy install -p roles -r requirements.yml --force
          ansible-galaxy collection install -r requirements.yml --force-with-deps
          bash ./ci.sh
          ansible-playbook -i hosts_all.yml all.yml --syntax-check --vault-password-file ~/.ssh/.ansible_vault_pass -C
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/.ansible_vault_pass
