name: Deploy Ansible Templates

env:
  LANG: ja_JP.UTF-8

on:
  push:
    paths:
      - "ansible/**"
    branches:
      - main
      - 'releases/**'

jobs:
  ansible-deploy:
    runs-on: self-hosted
    container:
      image: ghcr.io/toshibe678/infra/ansible
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy ansible server
        env:
          TOSHI_KEY: ${{ secrets.TOSHI_KEY }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml --force-with-deps
          ansible-galaxy install -r requirements.yml -p roles --force
          bash ./ci.sh
          ansible-playbook -D -l shigure,mayu -i hosts_all.yml all.yml --vault-password-file ~/.ssh/.ansible_vault_pass -C
          ansible-playbook -l network_switch -i hosts_all.yml all.yml --vault-password-file ~/.ssh/.ansible_vault_pass -C
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/.ansible_vault_pass
