name: Ansible Docker image build and push

env:
  LANG: ja_JP.UTF-8
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  ansible_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

#      - name: Prepare Build Arg
#        id: prepare_build_arg
#        run: |
#          CURRENT_TAG=${GITHUB_REF#refs/tags/}
##          echo ::set-output name=CURRENT_TAG::${CURRENT_TAG}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./docker/ansible
          file: ./docker/ansible/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
#          build-args: |
#            BUNDLER_VERSION=${{ steps.prepare_build_arg.outputs.BUNDLER_VERSION }}

#/usr/bin/docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new --file ./docker/ansible/Dockerfile --iidfile /tmp/docker-build-push-nOqjt6/iidfile --label org.opencontainers.image.source=https://github.com/toshibe678/infra.git --platform linux/amd64,linux/arm64 --provenance mode=max,builder-id=https://github.com/toshibe678/infra/actions/runs/4525055154 --tag ghcr.io/toshibe678/ansible: --metadata-file /tmp/docker-build-push-nOqjt6/metadata-file --push ./docker/ansible
#ERROR: invalid tag "ghcr.io/toshibe678/ansible:": invalid reference format
#Error: buildx failed with: ERROR: invalid tag "ghcr.io/toshibe678/ansible:": invalid reference format

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
