name: oidc test
run-name: oidc test [${{github.event.number}}]
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: oidc test
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

#      - name: Auth to Google Cloud by OpenID Connect
#        uses: google-github-actions/auth@v2
#        with:
#          project_id: 'toshiclick'
#          workload_identity_provider: 'projects/189082996927/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
#          service_account: 'github-actions@toshiclick.iam.gserviceaccount.com'
#          access_token_lifetime: 300s

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::570339075110:role/GitHubActionsRole
          aws-region: us-east-1

#      - name: PR Agent action step
#        id: pragent
#        uses: Codium-ai/pr-agent@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          github_action.auto_review: "true"
#          github_action.auto_describe: "true"
#          github_action.auto_improve: "true"
